### ISSUE TITLE
Understand and modify the various constants.

### ISSUE THREAD

**Issue by SpandanKumarSahu** [Swarm-IITKgp/SimpleSwarmSimulator#1]
Some constants have been used in "Motion.h" file which encompasses a lot many things. Understand what the constants signify and change them to fine tune it.

@akshatpandya

**Comment by SpandanKumarSahu** [comment]
@pranitbauva1997 @npochhi I think the new code does away with the constants I defined. We can close this issue too.

**Comment by mankeyboy** [comment]
@pranitbauva1997 Where is this going?

**Comment by SpandanKumarSahu** [comment]
@mankeyboy Closing this.
